//
// *********************************************************
// *                                                       *
// * Copyright 1998-2022, Lazerus Laser Systems            *
// * Author: Michael G. Svob                               *
// *                                                       *
// * File Name: AbstractControl.h                          *
// * Description: This file contains the interface for the *
// *              CAbstractControl dialog class.           *
// *                                                       *
// * NOTE: Some or all of the code contained in this file  *
// *       was generated by the Visual Studio MFC          *
// *       framework, and modified by the author as        *
// *       necessary for this application.                 *
// *                                                       *
// * This code is distributed under the GNU Public License *
// * which can be found at...                              *
// *                                                       *
// * http://www.gnu.org/licenses/gpl.txt                   *
// *                                                       *
// *********************************************************
//

#if !defined(AFX_ABSTRACTCONTROL_H__1A560C7F_EDF0_466A_BBB9_27144FF3BD16__INCLUDED_)
#define AFX_ABSTRACTCONTROL_H__1A560C7F_EDF0_466A_BBB9_27144FF3BD16__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// AbstractControl.h : header file
//

#ifndef GLOBALS_H
#include "globals.h"
#endif

class CCheap3DView;

/////////////////////////////////////////////////////////////////////////////
// CAbstractControl dialog

 class CAbstractControl : public CDialog
{
	friend CCheap3DView;
// Construction
public:
	CAbstractControl(CWnd* pParent = NULL);   // standard constructor

// Dialog Data
	//{{AFX_DATA(CAbstractControl)
	enum { IDD = IDD_ABS_CONTROL_DIALOG };
	CSliderCtrl	m_SliderGDepth;
	CSliderCtrl	m_SliderZAxisOffset;
	CSliderCtrl	m_SliderAbsPtsPerFrame;
	CSliderCtrl	m_SliderZAxisGain;
	CSliderCtrl	m_SliderBlankSpot;
	CSliderCtrl	m_SliderFactor7;
	CSliderCtrl	m_SliderFactor6;
	CSliderCtrl	m_SliderFactor5;
	CSliderCtrl	m_SliderFactor4;
	CSliderCtrl	m_SliderFactor3;
	CSliderCtrl	m_SliderRedOffset;
	CSliderCtrl	m_SliderGreenOffset;
	CSliderCtrl	m_SliderBlueOffset;
	CSliderCtrl	m_SliderColorSpeed;
	CSliderCtrl	m_SliderBlankSpeed;
	CSliderCtrl	m_SliderFactor2;
	CSliderCtrl	m_SliderFactor1;
	CSliderCtrl	m_SliderZzChangeNumber;
	CSliderCtrl	m_SliderGChangeNumber;
	CSliderCtrl	m_SliderZChangeNumber;
	UINT	m_EditGChangeNumber;
	UINT	m_EditZChangeNumber;
	UINT	m_EditZzChangeNumber;
	UINT	m_EditFactor1;
	UINT	m_EditFactor2;
	UINT	m_EditBlankSpeed;
	UINT	m_EditColorSpeed;
	UINT	m_EditBlueOffset;
	UINT	m_EditGreenOffset;
	UINT	m_EditRedOffset;
	UINT	m_EditFactor3;
	UINT	m_EditFactor4;
	UINT	m_EditFactor5;
	UINT	m_EditFactor6;
	UINT	m_EditFactor7;
	UINT	m_EditBlankSpot;
	int		m_AbstractPattern;
	int		m_ZAxis;
	UINT	m_EditZAxisGain;
	UINT	m_EditAbsPtsPerFrame;
	UINT	m_EditZAxisOffset;
	BOOL	m_UsePalette;
	UINT	m_EditGDepth;
	int		m_RadioGShape;
	int		m_ColorShift;
	//}}AFX_DATA


// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CAbstractControl)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
	//}}AFX_VIRTUAL

// Implementation
protected:

	// Generated message map functions
	//{{AFX_MSG(CAbstractControl)
	afx_msg void OnClose();
	afx_msg void OnCloseButton();
	afx_msg void OnVScroll(UINT nSBCode, UINT nPos, CScrollBar* pScrollBar);
	afx_msg void OnAbsPattern1();
	afx_msg void OnAbsPattern2();
	afx_msg void OnAbsPattern3();
	afx_msg void OnAbsPattern4();
	afx_msg void OnAbsPattern5();
	afx_msg void OnAbsPattern6();
	afx_msg void OnAbsPattern7();
	afx_msg void OnAbsPattern8();
	afx_msg void OnAbsZaxis1();
	afx_msg void OnAbsZaxis2();
	afx_msg void OnAbsZaxis3();
	afx_msg void OnAbsZaxis4();
	afx_msg void OnAbsZaxis5();
	afx_msg void OnAbsZaxis6();
	afx_msg void OnAbsZaxis7();
	afx_msg void OnAbsZaxis8();
	afx_msg void OnButtonAbsSave();
	afx_msg void OnCheckUsePalette();
	afx_msg void OnRadioEnvelopeSine();
	afx_msg void OnRadioEnvelopeSquare();
	afx_msg void OnAbsClrShift1();
	afx_msg void OnAbsClrShift2();
	afx_msg void OnAbsClrShift3();
	afx_msg void OnAbsClrShift4();
	afx_msg void OnAbsClrShift5();
	afx_msg void OnAbsClrShift6();
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()

	Abstract*   abstractPtr;
	void        InitControlSettings(void);

private:
	CCheap3DView*  parentPtr;

};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ABSTRACTCONTROL_H__1A560C7F_EDF0_466A_BBB9_27144FF3BD16__INCLUDED_)
