//
// *********************************************************
// *                                                       *
// * Copyright 1998-2022, Lazerus Laser Systems            *
// * Author: Michael G. Svob                               *
// *                                                       *
// * File Name: Cheap3D.h                                  *
// * Description: This file contains the interface for the *
// *              CCheap3DApp class.                       *
// *                                                       *
// * NOTE: This file was generated by MS Visual Studio,    *
// *       and modified by the author as necessary for     *
// *       the LFI Player application.
// *                                                       *
// * This code is distributed under the GNU Public License *
// * which can be found at...                              *
// *                                                       *
// * http://www.gnu.org/licenses/gpl.txt                   *
// *                                                       *
// *********************************************************
//

#if !defined(AFX_CHEAP3D_H__984EA605_2F4F_11D4_A333_E761A585437E__INCLUDED_)
#define AFX_CHEAP3D_H__984EA605_2F4F_11D4_A333_E761A585437E__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

#ifndef __AFXWIN_H__
    #error include 'stdafx.h' before including this file for PCH
#endif

#include "resource.h"       // main symbols
#include "Globals.h"
#include "Gem_pc.h"
#include "Routines.h"
#include "View.h"
#include "Frame.h"
#include "FrameSeq.h"
#include "Track.h"
#include "TrackLst.h"


/////////////////////////////////////////////////////////////////////////////
// CCheap3DApp:
// See Cheap3D.cpp for the implementation of this class
//

class CCheap3DApp : public CWinApp
{
public:
    CCheap3DApp();
    ~CCheap3DApp();

// Overrides
    // ClassWizard generated virtual function overrides
    //{{AFX_VIRTUAL(CCheap3DApp)
    public:
    virtual BOOL InitInstance();
    virtual int ExitInstance();

    //}}AFX_VIRTUAL

// Implementation

    //{{AFX_MSG(CCheap3DApp)
    afx_msg void OnAppAbout();
//	afx_msg void OnOpenIldaFile();
    //}}AFX_MSG
    DECLARE_MESSAGE_MAP()

};


/////////////////////////////////////////////////////////////////////////////

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHEAP3D_H__984EA605_2F4F_11D4_A333_E761A585437E__INCLUDED_)
