#if !defined(AFX_PREFPROPPAGEILDARECORDING_H__A811B787_3B3C_42DB_B7E3_E605A8F1FC42__INCLUDED_)
#define AFX_PREFPROPPAGEILDARECORDING_H__A811B787_3B3C_42DB_B7E3_E605A8F1FC42__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class CCheap3DView;

//
// *********************************************************
// *                                                       *
// * Copyright 1998-2022, Lazerus Laser Systems            *
// * Author: Michael G. Svob                               *
// *                                                       *
// * File Name: PrefProppageIldaRecording.h                *
// * Description: This file contains the interface for     *
// *              CPrefProppageIldaRecording class, which  *
// *              is the ILDA Recording preferences        *
// *              property page.                           *
// *                                                       *
// * NOTE: This file was generated by MS Visual Studio,    *
// *       and modified by the author as necessary for     *
// *       the LFI Player application.
// *                                                       *
// * This code is distributed under the GNU Public License *
// * which can be found at...                              *
// *                                                       *
// * http://www.gnu.org/licenses/gpl.txt                   *
// *                                                       *
// *********************************************************
//

class CPrefProppageIldaRecording : public CPropertyPage
{
	DECLARE_DYNCREATE(CPrefProppageIldaRecording)

// Construction
public:
	CPrefProppageIldaRecording();
	~CPrefProppageIldaRecording();
	void InitialUpdate(); 
    BOOL OnSetActive();

    CCheap3DView* parentPtr;

// Dialog Data
	//{{AFX_DATA(CPrefProppageIldaRecording)
	enum { IDD = IDD_PREF_PROPPAGE_ILDA_REC };
	UINT	m_EditNumberOfFrames2Record;
	int		m_RadioRecordPaletteType;
	int		m_RadioRecordViewType;
	//}}AFX_DATA


// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CPrefProppageIldaRecording)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
	//}}AFX_VIRTUAL

// Implementation
protected:

	// Generated message map functions
	//{{AFX_MSG(CPrefProppageIldaRecording)
	afx_msg void OnUpdateEditNumFrames2record();
	afx_msg void OnRecordPalettePangolin();
	afx_msg void OnRecordPaletteLaserIllusions();
	afx_msg void OnRecordPaletteILDA();
	afx_msg void OnRecordPaletteX29();
	afx_msg void OnRecordPaletteTrueColor();
	afx_msg void OnRecordViewEye();
	afx_msg void OnRecordViewWorld();
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PREFPROPPAGEILDARECORDING_H__A811B787_3B3C_42DB_B7E3_E605A8F1FC42__INCLUDED_)
