#if !defined(AFX_PREFPROPPAGEDISPLAYTIMER_H__6D6ED1B2_0A56_4179_A462_56603A2E9125__INCLUDED_)
#define AFX_PREFPROPPAGEDISPLAYTIMER_H__6D6ED1B2_0A56_4179_A462_56603A2E9125__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class CCheap3DView;

//
// *********************************************************
// *                                                       *
// * Copyright 1998-2022, Lazerus Laser Systems            *
// * Author: Michael G. Svob                               *
// *                                                       *
// * File Name: PrefProppageDisplayTimer.h                 *
// * Description: This file contains the interface for     *
// *              CPrefProppageDisplayTimer class, which   *
// *              is the Display Timer preferences         *
// *              property page.                           *
// *                                                       *
// * NOTE: This file was generated by MS Visual Studio,    *
// *       and modified by the author as necessary for     *
// *       the LFI Player application.
// *                                                       *
// * This code is distributed under the GNU Public License *
// * which can be found at...                              *
// *                                                       *
// * http://www.gnu.org/licenses/gpl.txt                   *
// *                                                       *
// *********************************************************
//

class CPrefProppageDisplayTimer : public CPropertyPage
{
	DECLARE_DYNCREATE(CPrefProppageDisplayTimer)

// Construction
public:
	CPrefProppageDisplayTimer();
	~CPrefProppageDisplayTimer();
    BOOL OnSetActive();

	CCheap3DView* parentPtr;

// Dialog Data
	//{{AFX_DATA(CPrefProppageDisplayTimer)
	enum { IDD = IDD_PREF_PROPPAGE_DISPLAY_TIMER };
	CSliderCtrl	m_SliderDisplayTimerValue;
    CSliderCtrl m_SliderPointsPerSecond;
	UINT	m_EditDisplayTimerValue;
    UINT    m_EditPointsPerSecond;
	//}}AFX_DATA


// Overrides
	// ClassWizard generate virtual function overrides
	//{{AFX_VIRTUAL(CPrefProppageDisplayTimer)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
	//}}AFX_VIRTUAL

// Implementation
protected:

	// Generated message map functions
	//{{AFX_MSG(CPrefProppageDisplayTimer)
	afx_msg void OnHScroll(UINT nSBCode, UINT nPos, CScrollBar* pScrollBar);
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()

};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PREFPROPPAGEDISPLAYTIMER_H__6D6ED1B2_0A56_4179_A462_56603A2E9125__INCLUDED_)
