//
// *********************************************************
// *                                                       *
// * Copyright 1998-2022, Lazerus Laser Systems            *
// * Author: Michael G. Svob                               *
// *                                                       *
// * File Name: Preferences.cpp                            *
// * Description: Implementation of the CPreferences       *
// * class, which is the dialog for setting user           *
// * preferences.                                          *
// *                                                       *
// * NOTE: This file was generated by MS Visual Studio,    *
// *       and modified by the author as necessary for     *
// *       the LFI Player application.
// *                                                       *
// * This code is distributed under the GNU Public License *
// * which can be found at...                              *
// *                                                       *
// * http://www.gnu.org/licenses/gpl.txt                   *
// *                                                       *
// *********************************************************
//

#include "stdafx.h"
#include "Cheap3D.h"
#include "Preferences.h"
#include "Cheap3DView.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#undef THIS_FILE
static char THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// CPreferences dialog


CPreferences::CPreferences(CWnd* pParent /*=NULL*/)
//    : CPropertySheet(AFX_IDS_APP_TITLE, pParent)
    : CPropertySheet("LFI Player Preferences", pParent)
{
	parentPtr = (CCheap3DView*)pParent;

    displayTimerPropertyPage.parentPtr  = parentPtr;
    colorPropertyPage.parentPtr         = parentPtr;
    ildaRecordingPropertyPage.parentPtr = parentPtr;
	liveControlPropertyPage.parentPtr   = parentPtr;
	beamViewPropertyPage.parentPtr      = parentPtr;
	outputPropertyPage.parentPtr        = parentPtr;
	comSettingsPropertyPage.parentPtr   = parentPtr;


	AddPage(&outputPropertyPage);
	AddPage(&displayTimerPropertyPage);
	AddPage(&colorPropertyPage);
	AddPage(&liveControlPropertyPage);
	AddPage(&beamViewPropertyPage);
	AddPage(&ildaRecordingPropertyPage);
    AddPage(&comSettingsPropertyPage);

	//{{AFX_DATA_INIT(CPreferences)
	//}}AFX_DATA_INIT
}

void CPreferences::DoDataExchange(CDataExchange* pDX)
{
	CPropertySheet::DoDataExchange(pDX);
	//{{AFX_DATA_MAP(CPreferences)
	//}}AFX_DATA_MAP
}


BEGIN_MESSAGE_MAP(CPreferences, CPropertySheet)
	//{{AFX_MSG_MAP(CPreferences)
	ON_WM_CLOSE()
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()

/////////////////////////////////////////////////////////////////////////////
// CPreferences message handlers

// void CPreferences::OnOK() 
// {
//	// TODO: Add extra validation here
//	parentPtr->preferencesDialog = 0;
//	DestroyWindow();
//	delete(this);
//	
//	CPropertySheet::OnOK();
// }

// void CPreferences::OnCancel() 
// {
//	// TODO: Add extra cleanup here
//	parentPtr->preferencesDialog = 0;
//	DestroyWindow();
//	delete(this);
//	
//	CPropertySheet::OnCancel();
// }


void CPreferences::OnClose() 
{
	// TODO: Add your message handler code here and/or call default	
	CPropertySheet::OnClose();
}
