#if !defined(AFX_PREFPROPPAGECOLOR_H__748DCB68_62E4_4B4E_9F4C_FE1277ECFF11__INCLUDED_)
#define AFX_PREFPROPPAGECOLOR_H__748DCB68_62E4_4B4E_9F4C_FE1277ECFF11__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class CCheap3DView;

//
// *********************************************************
// *                                                       *
// * Copyright 1998-2022, Lazerus Laser Systems            *
// * Author: Michael G. Svob                               *
// *                                                       *
// * File Name: PrefProppageColor.h                        *
// * Description: This file contains the interface for     *
// *              CPrefProppageColor class, which is       *
// *              the Color preferences property page.     *
// *                                                       *
// * NOTE: This file was generated by MS Visual Studio,    *
// *       and modified by the author as necessary for     *
// *       the LFI Player application.
// *                                                       *
// * This code is distributed under the GNU Public License *
// * which can be found at...                              *
// *                                                       *
// * http://www.gnu.org/licenses/gpl.txt                   *
// *                                                       *
// *********************************************************
//

class CPrefProppageColor : public CPropertyPage
{
	DECLARE_DYNCREATE(CPrefProppageColor)

// Construction
public:
	CPrefProppageColor();
//	CPrefProppageColor(CWnd* pParent);
	~CPrefProppageColor();
    BOOL OnSetActive();

    CCheap3DView* parentPtr;

// Dialog Data
	//{{AFX_DATA(CPrefProppageColor)
	enum { IDD = IDD_PREF_PROPPAGE_COLOR };
	int		m_RadioDisplayColorMode;
    CSliderCtrl m_SliderMasterRed;
    CSliderCtrl m_SliderMasterGreen;
    CSliderCtrl m_SliderMasterBlue;
	UINT	m_EditMasterRed;
	UINT	m_EditMasterGreen;
	UINT	m_EditMasterBlue;
    CSliderCtrl m_SliderTTLThresholdRed;
    CSliderCtrl m_SliderTTLThresholdGreen;
    CSliderCtrl m_SliderTTLThresholdBlue;
	UINT	m_EditTTLThresholdRed;
	UINT	m_EditTTLThresholdGreen;
	UINT	m_EditTTLThresholdBlue;
	//}}AFX_DATA


// Overrides
	// ClassWizard generate virtual function overrides
	//{{AFX_VIRTUAL(CPrefProppageColor)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
	//}}AFX_VIRTUAL

// Implementation
protected:

	// Generated message map functions
	//{{AFX_MSG(CPrefProppageColor)
	afx_msg void OnPrefColorNorm();
	afx_msg void OnPrefColorMono();
	afx_msg void OnPrefColorInv();
	afx_msg void OnPrefColorGray();
	afx_msg void OnPrefColorCVL();
	afx_msg void OnPrefColorTTL();
	afx_msg void OnPrefColorRGInvTTL();
	afx_msg void OnHScroll(UINT nSBCode, UINT nPos, CScrollBar* pScrollBar);
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()

};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PREFPROPPAGECOLOR_H__748DCB68_62E4_4B4E_9F4C_FE1277ECFF11__INCLUDED_)
