#if !defined(AFX_PREFPROPPAGEOUTPUT_H__754A0724_5136_49E8_9D31_FA15770A24C1__INCLUDED_)
#define AFX_PREFPROPPAGEOUTPUT_H__754A0724_5136_49E8_9D31_FA15770A24C1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

class CCheap3DView;

//
// *********************************************************
// *                                                       *
// * Copyright 1998-2022, Lazerus Laser Systems            *
// * Author: Michael G. Svob                               *
// *                                                       *
// * File Name: PrefProppageOutput.h                       *
// * Description: This file contains the interface for     *
// *              CPrefProppageOutput class, which is      *
// *              the Output preferences property page.    *
// *                                                       *
// * NOTE: This file was generated by MS Visual Studio,    *
// *       and modified by the author as necessary for     *
// *       the LFI Player application.
// *                                                       *
// * This code is distributed under the GNU Public License *
// * which can be found at...                              *
// *                                                       *
// * http://www.gnu.org/licenses/gpl.txt                   *
// *                                                       *
// *********************************************************
//

class CPrefProppageOutput : public CPropertyPage
{
	DECLARE_DYNCREATE(CPrefProppageOutput)

// Construction
public:
	CPrefProppageOutput();
	~CPrefProppageOutput();
    BOOL OnSetActive();

	CCheap3DView* parentPtr;

// Dialog Data
	//{{AFX_DATA(CPrefProppageOutput)
	enum { IDD = IDD_PREF_PROPPAGE_OUTPUT };
	CSliderCtrl	m_SliderVerticalScale;
	CSliderCtrl	m_SliderGlobalTrackDelay;
	CSliderCtrl	m_SliderLaserScale;
	CSliderCtrl	m_SliderBlankingShift;    
	BOOL	m_DisplayLaser;
	BOOL	m_DisplayScreen;
	BOOL	m_ScriptRepeat;
	UINT    m_LaserScale;
	UINT	m_VerticalScale;
	UINT    m_GlobalTrackDelay;
    INT     m_BlankingShift;
	BOOL	m_CheckInvertX;
	BOOL	m_CheckInvertY;
	BOOL	m_CheckScreenInvert;
    BOOL    m_FlickerFree;
    BOOL    m_InvertBlanking;
	BOOL    m_BlankClipView;
		// NOTE - ClassWizard will add data members here.
		//    DO NOT EDIT what you see in these blocks of generated code !
	//}}AFX_DATA


// Overrides
	// ClassWizard generate virtual function overrides
	//{{AFX_VIRTUAL(CPrefProppageOutput)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
	//}}AFX_VIRTUAL

// Implementation
protected:
	// Generated message map functions
	//{{AFX_MSG(CPrefProppageOutput)
	afx_msg void OnHScroll(UINT nSBCode, UINT nPos, CScrollBar* pScrollBar);
	afx_msg void OnPrefInvertx();
	afx_msg void OnPrefInverty();
	afx_msg void OnPrefScrnInvert();
	afx_msg void OnCheckDisplayLaser();
	afx_msg void OnCheckDisplayScreen();
	afx_msg void OnCheckScriptRepeat();
    afx_msg void OnCheckFlickerFree();
    afx_msg void OnCheckInvertBlanking();
    afx_msg void OnCheckBlankClipView();
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()

};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PREFPROPPAGEOUTPUT_H__754A0724_5136_49E8_9D31_FA15770A24C1__INCLUDED_)
