#ifdef LEGACY_OUTPUT
#if !defined(AFX_SELECTPORT_H__0C5A36A1_3CAB_11D4_A333_E761A585437E__INCLUDED_)
#define AFX_SELECTPORT_H__0C5A36A1_3CAB_11D4_A333_E761A585437E__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000

//
// *********************************************************
// *                                                       *
// * Copyright 1998-2022, Lazerus Laser Systems            *
// * Author: Michael G. Svob                               *
// *                                                       *
// * File Name: SelectPort.h                               *
// * Description: This file contains the interface for the *
// *              CSelectPort dialog class.                *
// *                                                       *
// * NOTE: This file was generated by MS Visual Studio,    *
// *       and modified by the author as necessary for     *
// *       the LFI Player application.
// *                                                       *
// * This code is distributed under the GNU Public License *
// * which can be found at...                              *
// *                                                       *
// * http://www.gnu.org/licenses/gpl.txt                   *
// *                                                       *
// *********************************************************
//

#include "Cheap3DView.h"

class CSelectPort : public CDialog
{
// Construction
public:
	CSelectPort(CWnd* pParent = NULL);   // standard constructor

// Dialog Data
	//{{AFX_DATA(CSelectPort)
	enum { IDD = IDD_SELECT_PORT_DIALOG };
	int		m_PortButtonSelected;
	//}}AFX_DATA


// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(CSelectPort)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
	//}}AFX_VIRTUAL

// Implementation
protected:
    CCheap3DView* parentPtr;

	// Generated message map functions
	//{{AFX_MSG(CSelectPort)
	afx_msg void OnRadioPort200();
	afx_msg void OnRadioPort220();
	afx_msg void OnRadioPort240();
	afx_msg void OnRadioPort260();
	afx_msg void OnRadioPort2a0();
	afx_msg void OnRadioPort2c0();
	afx_msg void OnRadioPort300();
	afx_msg void OnRadioPort320();
	afx_msg void OnRadioPort340();
	afx_msg void OnRadioPort360();
	afx_msg void OnRadioPort3a0();
	afx_msg void OnRadioPort3c0();
	afx_msg void OnRadioPort280();
	afx_msg void OnRadioPort2e0();
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SELECTPORT_H__0C5A36A1_3CAB_11D4_A333_E761A585437E__INCLUDED_)
#endif
